steps:
  # Install dependencies
  - name: "node:22"
    entrypoint: npm
    args: ["install"]
    dir: "boom"
    id: "install"

  # Build the application
  - name: "node:22"
    entrypoint: npm
    args: ["run", "build"]
    dir: "boom"
    id: "build"
    waitFor: ["install"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy boom-service \
          --source ./boom \
          --region europe-southwest1 \
          --platform managed \
          --allow-unauthenticated \
          --project boom-456608
    id: "deploy"
    waitFor: ["build"]

# Set timeout for the entire build process
timeout: "1800s" # 30 minutes
