steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        "-t",
        "europe-southwest1-docker.pkg.dev/boom-456608/boom/my-image:latest",
        "-f",
        "boom/docker/prod/Dockerfile",
        "boom", # Set the build context to the boom directory
      ]

# Push the container image to Artifact Registry
images:
  - "europe-southwest1-docker.pkg.dev/boom-456608/boom/my-image:latest"

# Configure build options
options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s" # Set a reasonable timeout (30 minutes)
