steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build", # Build the Docker image
        "-t", # Flag to specify the image name and tag
        "europe-southwest1-docker.pkg.dev/boom-456608/boom/my-image:latest", # Specify the image name and tag
        "-f", # Flag to enable Dockerfile path specification
        "boom/docker/prod/Dockerfile", # Specify the Dockerfile path
        "boom", # Set the build context to the boom directory
      ]

# Push the container image to Artifact Registry
images:
  - "europe-southwest1-docker.pkg.dev/boom-456608/boom/my-image:latest"

# Configure build options
options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s" # Set a reasonable timeout (30 minutes)
