services:
  boom:
    container_name: boom_container
    image: boom_image
    build:
      context: ./boom
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8080:3000" # Host port 8080 maps to container port 3000
    environment:
      - NODE_ENV=development
    env_file:
      - ./boom/.env
    volumes:
      - ./boom:/app # Share the host machine's Dashboard directory with the container's /app directory
      - node_modules_volume:/app/node_modules # Use a named volume for node_modules # This is done to ensure that the node_modules directory inside the container is isolated and not affected by the host machine's environment. It can also prevent issues with modules that are platform-specific.

volumes: # Named volumes must be defined under the volumes section
  node_modules_volume:
    driver: local # Use the default driver (local) # This is the default driver for local volumes, ensuring compatibility with the host system.
